# Service
kind: Service
metadata:
  name: current-projects
  namespace: current-projects
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: current-projects
